
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: 20
    - run: yarn install
    - run: npm i -g npm@latest
    - run: npm run build

  eslint:
    name: ESLint
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: 20
    - run: yarn install
    - run: npm i -g npm@latest
    - run: npm run eslint

  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: 20
    - run: yarn install

  prettier:
    name: Prettier
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: 20
    - run: yarn install
    - run: npm i -g npm@latest
    - run: npm run prettier
