
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
      working-directory: ./packages/react-three-cannon
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: packages/react-three-cannon/dist

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install
    - run: yarn run prettier

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install
    - run: yarn run eslint

  example-build:
    name: Example Build
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: packages/react-three-cannon/dist
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
      working-directory: ./packages/react-three-cannon-examples
